spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8092

resto:
  order:
    kafka:
      topic:
        name: orders
      groupid: Mayur
eureka:
  client:
    serverUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}
    instance:
      preferIpAddress=true
